export interface City {
  id: string;
  name: string;
  country: string;
  levelsUrl: string;
  costOfLivingIndex: number;
}

export const cities: Record<string, City> = {
  'new-york': {
    id: 'new-york',
    name: 'New York',
    country: 'united states',
    levelsUrl: 'new-york-usa',
    costOfLivingIndex: 100,
  },
  sf: {
    id: 'sf',
    name: 'San Francisco',
    country: 'united states',
    levelsUrl: 'san-francisco-bay-area',
    costOfLivingIndex: 100,
  },
  london: {
    id: 'london',
    name: 'London',
    country: 'united kingdom',
    levelsUrl: 'london-metro-area',
    costOfLivingIndex: 100,
  },
  dubai: {
    id: 'dubai',
    name: 'Dubai',
    country: 'united arab emirates',
    levelsUrl: 'greater-dubai-area',
    costOfLivingIndex: 100,
  },
  berlin: {
    id: 'berlin',
    name: 'Berlin',
    country: 'germany',
    levelsUrl: 'berlin-metropolitan-region',
    costOfLivingIndex: 100,
  },
  barcelona: {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'spain',
    levelsUrl: 'greater-barcelona-area',
    costOfLivingIndex: 100,
  },
  zurich: {
    id: 'zurich',
    name: 'Zurich',
    country: 'switzerland',
    levelsUrl: 'greater-zurich-area',
    costOfLivingIndex: 100,
  },
  seattle: {
    id: 'seattle',
    name: 'Seattle',
    country: 'united states',
    levelsUrl: 'greater-seattle-area',
    costOfLivingIndex: 100,
  },
  sanDiego: {
    id: 'san-diego',
    name: 'San Diego',
    country: 'united states',
    levelsUrl: 'greater-san-diego-area',
    costOfLivingIndex: 100,
  },
  amsterdam: {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'netherlands',
    levelsUrl: 'greater-amsterdam-area',
    costOfLivingIndex: 100,
  },
  portland: {
    id: 'portland',
    name: 'Portland',
    country: 'united states',
    levelsUrl: 'greater-portland-area',
    costOfLivingIndex: 100,
  },
  'tel-aviv': {
    id: 'tel-aviv',
    name: 'Tel Aviv-Yafo',
    country: 'israel',
    levelsUrl: 'tel-aviv-metropolitan-area',
    costOfLivingIndex: 100,
  },
  vancouver: {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'canada',
    levelsUrl: 'greater-vancouver',
    costOfLivingIndex: 100,
  },
  sydney: {
    id: 'sydney',
    name: 'Sydney',
    country: 'australia',
    levelsUrl: 'greater-sydney',
    costOfLivingIndex: 100,
  },
  'abu-dhabi': {
    id: 'abu-dhabi',
    name: 'Abu Dhabi',
    country: 'united arab emirates',
    levelsUrl: 'united-arab-emirates',
    costOfLivingIndex: 100,
  },
  singapore: {
    id: 'singapore',
    name: 'Singapore',
    country: 'singapore',
    levelsUrl: 'singapore',
    costOfLivingIndex: 100,
  },
  dublin: {
    id: 'dublin',
    name: 'Dublin',
    country: 'ireland',
    levelsUrl: 'greater-dublin-area',
    costOfLivingIndex: 100,
  },
  luxembourg: {
    id: 'luxembourg',
    name: 'Luxembourg',
    country: 'luxembourg',
    levelsUrl: 'luxembourg',
    costOfLivingIndex: 100,
  },
  copenhagen: {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'denmark',
    levelsUrl: 'denmark',
    costOfLivingIndex: 100,
  },
  cambridge: {
    id: 'cambridge',
    name: 'Cambridge',
    country: 'united kingdom',
    levelsUrl: 'greater-cambridge-area',
    costOfLivingIndex: 100,
  },
  geneva: {
    id: 'geneva',
    name: 'Geneva',
    country: 'switzerland',
    levelsUrl: 'switzerland',
    costOfLivingIndex: 100,
  },
  'los-angeles': {
    id: 'los-angeles',
    name: 'Los Angeles',
    country: 'united states',
    levelsUrl: 'greater-los-angeles-area',
    costOfLivingIndex: 100,
  },
  austin: {
    id: 'austin',
    name: 'Austin',
    country: 'united states',
    levelsUrl: 'greater-austin-area',
    costOfLivingIndex: 100,
  },
  boston: {
    id: 'boston',
    name: 'Boston',
    country: 'united states',
    levelsUrl: 'greater-boston-area',
    costOfLivingIndex: 100,
  },
  toronto: {
    id: 'toronto',
    name: 'Toronto',
    country: 'canada',
    levelsUrl: 'greater-toronto-area',
    costOfLivingIndex: 100,
  },
};
