type RegionType = (typeof REGIONS)[keyof typeof REGIONS];

export const REGIONS = {
  EUROPE: 'Europe',
  NORTH_AMERICA: 'North America',
  SOUTH_AMERICA: 'South America',
  ASIA: 'Asia',
  MIDDLE_EAST: 'Middle East',
  OCEANIA: 'Oceania',
  AFRICA: 'Africa',
} as const;

export interface City {
  id: string;
  name: string;
  country: string;
  levelsUrl: string;
  costOfLivingIndex: number;
  region: RegionType;
}

export const cities: Record<string, City> = {
  'new-york': {
    id: 'new-york',
    name: 'New York',
    country: 'United States',
    levelsUrl: 'new-york-usa',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  sf: {
    id: 'sf',
    name: 'San Francisco',
    country: 'United States',
    levelsUrl: 'san-francisco-bay-area',
    costOfLivingIndex: 85.3,
    region: REGIONS.NORTH_AMERICA,
  },
  london: {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    levelsUrl: 'london-metro-area',
    costOfLivingIndex: 73,
    region: REGIONS.EUROPE,
  },
  dubai: {
    id: 'dubai',
    name: 'Dubai',
    country: 'United Arab Emirates',
    levelsUrl: 'greater-dubai-area',
    costOfLivingIndex: 55.1,
    region: REGIONS.MIDDLE_EAST,
  },
  berlin: {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    levelsUrl: 'berlin-metropolitan-region',
    costOfLivingIndex: 47.6,
    region: REGIONS.EUROPE,
  },
  barcelona: {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    levelsUrl: 'greater-barcelona-area',
    costOfLivingIndex: 41.9,
    region: REGIONS.EUROPE,
  },
  zurich: {
    id: 'zurich',
    name: 'Zurich',
    country: 'Switzerland',
    levelsUrl: 'greater-zurich-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  seattle: {
    id: 'seattle',
    name: 'Seattle',
    country: 'United States',
    levelsUrl: 'greater-seattle-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  'san-diego': {
    id: 'san-diego',
    name: 'San Diego',
    country: 'United States',
    levelsUrl: 'greater-san-diego-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  amsterdam: {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    levelsUrl: 'greater-amsterdam-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  portland: {
    id: 'portland',
    name: 'Portland',
    country: 'United States',
    levelsUrl: 'greater-portland-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  'tel-aviv': {
    id: 'tel-aviv',
    name: 'Tel Aviv-Yafo',
    country: 'Israel',
    levelsUrl: 'tel-aviv-metropolitan-area',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  vancouver: {
    id: 'vancouver',
    name: 'Vancouver',
    country: 'Canada',
    levelsUrl: 'greater-vancouver',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  sydney: {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    levelsUrl: 'greater-sydney',
    costOfLivingIndex: 100,
    region: REGIONS.OCEANIA,
  },
  'abu-dhabi': {
    id: 'abu-dhabi',
    name: 'Abu Dhabi',
    country: 'United Arab Emirates',
    levelsUrl: 'united-arab-emirates',
    costOfLivingIndex: 100,
    region: REGIONS.MIDDLE_EAST,
  },
  singapore: {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    levelsUrl: 'singapore',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  dublin: {
    id: 'dublin',
    name: 'Dublin',
    country: 'Ireland',
    levelsUrl: 'greater-dublin-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  luxembourg: {
    id: 'luxembourg',
    name: 'Luxembourg',
    country: 'Luxembourg',
    levelsUrl: 'luxembourg',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  copenhagen: {
    id: 'copenhagen',
    name: 'Copenhagen',
    country: 'Denmark',
    levelsUrl: 'denmark',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  cambridge: {
    id: 'cambridge',
    name: 'Cambridge',
    country: 'United Kingdom',
    levelsUrl: 'greater-cambridge-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  geneva: {
    id: 'geneva',
    name: 'Geneva',
    country: 'Switzerland',
    levelsUrl: 'switzerland',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  'los-angeles': {
    id: 'los-angeles',
    name: 'Los Angeles',
    country: 'United States',
    levelsUrl: 'greater-los-angeles-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  austin: {
    id: 'austin',
    name: 'Austin',
    country: 'United States',
    levelsUrl: 'greater-austin-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  boston: {
    id: 'boston',
    name: 'Boston',
    country: 'United States',
    levelsUrl: 'greater-boston-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  toronto: {
    id: 'toronto',
    name: 'Toronto',
    country: 'Canada',
    levelsUrl: 'greater-toronto-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  lisbon: {
    id: 'lisbon',
    name: 'Lisbon',
    country: 'Portugal',
    levelsUrl: 'lisbon-metro-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  chicago: {
    id: 'chicago',
    name: 'Chicago',
    country: 'United States',
    levelsUrl: 'greater-chicago-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  paris: {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    levelsUrl: 'greater-paris-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  miami: {
    id: 'miami',
    name: 'Miami',
    country: 'United States',
    levelsUrl: 'miami-ft-lauderdale-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  bengaluru: {
    id: 'bengaluru',
    name: 'Bangalore',
    country: 'India',
    levelsUrl: 'greater-bengaluru',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  atlanta: {
    id: 'atlanta',
    name: 'Atlanta',
    country: 'United States',
    levelsUrl: 'atlanta-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  philadelphia: {
    id: 'philadelphia',
    name: 'Philadelphia',
    country: 'United States',
    levelsUrl: 'philadelphia-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  stockholm: {
    id: 'stockholm',
    name: 'Stockholm',
    country: 'Sweden',
    levelsUrl: 'greater-stockholm',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  nashville: {
    id: 'nashville',
    name: 'Nashville',
    country: 'United States',
    levelsUrl: 'nashville-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  montreal: {
    id: 'montreal',
    name: 'Montreal',
    country: 'Canada',
    levelsUrl: 'greater-montreal',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  vienna: {
    id: 'vienna',
    name: 'Vienna',
    country: 'Austria',
    levelsUrl: 'vienna-metropolitan-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  'salt-lake-city': {
    id: 'salt-lake-city',
    name: 'Salt Lake City',
    country: 'United States',
    levelsUrl: 'salt-lake-city-greater-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  melbourne: {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    levelsUrl: 'greater-melbourne-area',
    costOfLivingIndex: 100,
    region: REGIONS.OCEANIA,
  },
  dallas: {
    id: 'dallas',
    name: 'Dallas',
    country: 'United States',
    levelsUrl: 'greater-dallas-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  helsinki: {
    id: 'helsinki',
    name: 'Helsinki',
    country: 'Finland',
    levelsUrl: 'greater-helsinki',
    costOfLivingIndex: 46.9,
    region: REGIONS.EUROPE,
  },
  'st-louis': {
    id: 'st-louis',
    name: 'St. Louis',
    country: 'United States',
    levelsUrl: 'st-louis-area',
    costOfLivingIndex: 48.9,
    region: REGIONS.NORTH_AMERICA,
  },
  houston: {
    id: 'houston',
    name: 'Houston',
    country: 'United States',
    levelsUrl: 'greater-houston-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  oslo: {
    id: 'oslo',
    name: 'Oslo',
    country: 'Norway',
    levelsUrl: 'greater-oslo-region',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  munich: {
    id: 'munich',
    name: 'Munich',
    country: 'Germany',
    levelsUrl: 'munich-metro-region',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  calgary: {
    id: 'calgary',
    name: 'Calgary',
    country: 'Canada',
    levelsUrl: 'greater-calgary-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  orlando: {
    id: 'orlando',
    name: 'Orlando',
    country: 'United States',
    levelsUrl: 'orlando-daytona-bch-melbrn-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  riyadh: {
    id: 'riyadh',
    name: 'Riyadh',
    country: 'Saudi Arabia',
    levelsUrl: 'saudi-arabia',
    costOfLivingIndex: 100,
    region: REGIONS.MIDDLE_EAST,
  },
  minneapolis: {
    id: 'minneapolis',
    name: 'Minneapolis',
    country: 'United States',
    levelsUrl: 'minneapolis-st-paul-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  cairo: {
    id: 'cairo',
    name: 'Cairo',
    country: 'Egypt',
    levelsUrl: 'greater-cairo',
    costOfLivingIndex: 100,
    region: REGIONS.AFRICA,
  },
  edinburgh: {
    id: 'edinburgh',
    name: 'Edinburgh',
    country: 'United Kingdom',
    levelsUrl: 'edinburgh-metro-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  ottawa: {
    id: 'ottawa',
    name: 'Ottawa',
    country: 'Canada',
    levelsUrl: 'greater-ottawa-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  auckland: {
    id: 'auckland',
    name: 'Auckland',
    country: 'New Zealand',
    levelsUrl: 'auckland-region',
    costOfLivingIndex: 100,
    region: REGIONS.OCEANIA,
  },
  manchester: {
    id: 'manchester',
    name: 'Manchester',
    country: 'United Kingdom',
    levelsUrl: 'greater-manchester',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  baltimore: {
    id: 'baltimore',
    name: 'Baltimore',
    country: 'United States',
    levelsUrl: 'baltimore-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  brisbane: {
    id: 'brisbane',
    name: 'Brisbane',
    country: 'Australia',
    levelsUrl: 'south-east-queensland-metro-region',
    costOfLivingIndex: 100,
    region: REGIONS.OCEANIA,
  },
  madrid: {
    id: 'madrid',
    name: 'Madrid',
    country: 'Spain',
    levelsUrl: 'madrid-metropolitan-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  denver: {
    id: 'denver',
    name: 'Denver',
    country: 'United States',
    levelsUrl: 'greater-denver-and-boulder-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  raleigh: {
    id: 'raleigh',
    name: 'Raleigh',
    country: 'United States',
    levelsUrl: 'raleigh-durham-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  tampa: {
    id: 'tampa',
    name: 'Tampa',
    country: 'United States',
    levelsUrl: 'tampa-st-pete-sarasota-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  milan: {
    id: 'milan',
    name: 'Milan',
    country: 'Italy',
    levelsUrl: 'italy',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  athens: {
    id: 'athens',
    name: 'Athens',
    country: 'Greece',
    levelsUrl: 'greece',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  hamburg: {
    id: 'hamburg',
    name: 'Hamburg',
    country: 'Germany',
    levelsUrl: 'hamburg-metro-region',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  bristol: {
    id: 'bristol',
    name: 'Bristol',
    country: 'United Kingdom',
    levelsUrl: 'greater-bristol',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  'las-vegas': {
    id: 'las-vegas',
    name: 'Las Vegas',
    country: 'United States',
    levelsUrl: 'las-vegas-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  mumbai: {
    id: 'mumbai',
    name: 'Mumbai',
    country: 'India',
    levelsUrl: 'mumbai-metropolitan-region',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  charlotte: {
    id: 'charlotte',
    name: 'Charlotte',
    country: 'United States',
    levelsUrl: 'charlotte-nc-greater-area',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  bangkok: {
    id: 'bangkok',
    name: 'Bangkok',
    country: 'Thailand',
    levelsUrl: 'bangkok-metro-region',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  'buenos-aires': {
    id: 'buenos-aires',
    name: 'Buenos Aires',
    country: 'Argentina',
    levelsUrl: 'greater-buenos-aires-region',
    costOfLivingIndex: 100,
    region: REGIONS.SOUTH_AMERICA,
  },
  'mexico-city': {
    id: 'mexico-city',
    name: 'Mexico City',
    country: 'Mexico',
    levelsUrl: 'mexico',
    costOfLivingIndex: 100,
    region: REGIONS.NORTH_AMERICA,
  },
  tokyo: {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    levelsUrl: 'greater-tokyo-area',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  'kuala-lumpur': {
    id: 'kuala-lumpur',
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    levelsUrl: 'greater-kuala-lumpur',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  medellin: {
    id: 'medellin',
    name: 'Medellin',
    country: 'Colombia',
    levelsUrl: 'colombia',
    costOfLivingIndex: 100,
    region: REGIONS.SOUTH_AMERICA,
  },
  istanbul: {
    id: 'istanbul',
    name: 'Istanbul',
    country: 'Turkey',
    levelsUrl: 'istanbul-metropolitan-municipality',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  porto: {
    id: 'porto',
    name: 'Porto',
    country: 'Portugal',
    levelsUrl: 'porto-district',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  'cape-town': {
    id: 'cape-town',
    name: 'Cape Town',
    country: 'South Africa',
    levelsUrl: 'greater-cape-town-region',
    costOfLivingIndex: 100,
    region: REGIONS.AFRICA,
  },
  seoul: {
    id: 'seoul',
    name: 'Seoul',
    country: 'South Korea',
    levelsUrl: 'seoul-capital-area',
    costOfLivingIndex: 100,
    region: REGIONS.ASIA,
  },
  santiago: {
    id: 'santiago',
    name: 'Santiago',
    country: 'Chile',
    levelsUrl: 'chile',
    costOfLivingIndex: 100,
    region: REGIONS.SOUTH_AMERICA,
  },
  belgrade: {
    id: 'belgrade',
    name: 'Belgrade',
    country: 'Serbia',
    levelsUrl: 'serbia',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  warsaw: {
    id: 'warsaw',
    name: 'Warsaw',
    country: 'Poland',
    levelsUrl: 'warsaw-metropolitan-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
  prague: {
    id: 'prague',
    name: 'Prague',
    country: 'Czech Republic',
    levelsUrl: 'prague-metropolitan-area',
    costOfLivingIndex: 100,
    region: REGIONS.EUROPE,
  },
};
