export interface CostOfLivingEntry {
  city: string;
  state?: string;
  country: string;
  index: number;
}

export interface CostOfLivingData {
  [key: string]: CostOfLivingEntry;
}

export const fallbackCostOfLiving: CostOfLivingData = {
  'zurich-switzerland': {
    city: 'Zurich',
    state: '',
    country: 'Switzerland',
    index: 85.4,
  },
  'lausanne-switzerland': {
    city: 'Lausanne',
    state: '',
    country: 'Switzerland',
    index: 76.2,
  },
  'geneva-switzerland': {
    city: 'Geneva',
    state: '',
    country: 'Switzerland',
    index: 82.3,
  },
  'basel-switzerland': {
    city: 'Basel',
    state: '',
    country: 'Switzerland',
    index: 75.2,
  },
  'new york-ny-united states': {
    city: 'New York',
    state: 'NY',
    country: 'United States',
    index: 100,
  },
  'bern-switzerland': {
    city: 'Bern',
    state: '',
    country: 'Switzerland',
    index: 68.9,
  },
  'san francisco-ca-united states': {
    city: 'San Francisco',
    state: 'CA',
    country: 'United States',
    index: 84.4,
  },
  'honolulu-hi-united states': {
    city: 'Honolulu',
    state: 'HI',
    country: 'United States',
    index: 73.3,
  },
  'san jose-ca-united states': {
    city: 'San Jose',
    state: 'CA',
    country: 'United States',
    index: 77.9,
  },
  'boston-ma-united states': {
    city: 'Boston',
    state: 'MA',
    country: 'United States',
    index: 78.2,
  },
  'reykjavik-iceland': {
    city: 'Reykjavik',
    state: '',
    country: 'Iceland',
    index: 64.6,
  },
  'washington-dc-united states': {
    city: 'Washington',
    state: 'DC',
    country: 'United States',
    index: 74.2,
  },
  'seattle-wa-united states': {
    city: 'Seattle',
    state: 'WA',
    country: 'United States',
    index: 69.2,
  },
  'singapore-singapore': {
    city: 'Singapore',
    state: '',
    country: 'Singapore',
    index: 73.2,
  },
  'london-united kingdom': {
    city: 'London',
    state: '',
    country: 'United Kingdom',
    index: 72.6,
  },
  'trondheim-norway': {
    city: 'Trondheim',
    state: '',
    country: 'Norway',
    index: 55.9,
  },
  'san diego-ca-united states': {
    city: 'San Diego',
    state: 'CA',
    country: 'United States',
    index: 72.7,
  },
  'oslo-norway': {
    city: 'Oslo',
    state: '',
    country: 'Norway',
    index: 56.6,
  },
  'los angeles-ca-united states': {
    city: 'Los Angeles',
    state: 'CA',
    country: 'United States',
    index: 70.2,
  },
  'sacramento-ca-united states': {
    city: 'Sacramento',
    state: 'CA',
    country: 'United States',
    index: 63.4,
  },
  'tel aviv-yafo-israel': {
    city: 'Tel Aviv-Yafo',
    state: '',
    country: 'Israel',
    index: 58.7,
  },
  'bergen-norway': {
    city: 'Bergen',
    state: '',
    country: 'Norway',
    index: 52.4,
  },
  'hong kong-hong kong (china)': {
    city: 'Hong Kong',
    state: '',
    country: 'Hong Kong (China)',
    index: 65.1,
  },
  'philadelphia-pa-united states': {
    city: 'Philadelphia',
    state: 'PA',
    country: 'United States',
    index: 58.9,
  },
  'chicago-il-united states': {
    city: 'Chicago',
    state: 'IL',
    country: 'United States',
    index: 64.2,
  },
  'miami-fl-united states': {
    city: 'Miami',
    state: 'FL',
    country: 'United States',
    index: 70.5,
  },
  'raleigh-nc-united states': {
    city: 'Raleigh',
    state: 'NC',
    country: 'United States',
    index: 61.4,
  },
  'copenhagen-denmark': {
    city: 'Copenhagen',
    state: '',
    country: 'Denmark',
    index: 57,
  },
  'denver-co-united states': {
    city: 'Denver',
    state: 'CO',
    country: 'United States',
    index: 61.9,
  },
  'atlanta-ga-united states': {
    city: 'Atlanta',
    state: 'GA',
    country: 'United States',
    index: 58.2,
  },
  'charlotte-nc-united states': {
    city: 'Charlotte',
    state: 'NC',
    country: 'United States',
    index: 61.7,
  },
  'tampa-fl-united states': {
    city: 'Tampa',
    state: 'FL',
    country: 'United States',
    index: 60.5,
  },
  'sydney-australia': {
    city: 'Sydney',
    state: '',
    country: 'Australia',
    index: 60.8,
  },
  'new orleans-la-united states': {
    city: 'New Orleans',
    state: 'LA',
    country: 'United States',
    index: 56.4,
  },
  'portland-or-united states': {
    city: 'Portland',
    state: 'OR',
    country: 'United States',
    index: 58.9,
  },
  'canberra-australia': {
    city: 'Canberra',
    state: '',
    country: 'Australia',
    index: 55.7,
  },
  'paris-france': {
    city: 'Paris',
    state: '',
    country: 'France',
    index: 55.1,
  },
  'espoo-finland': {
    city: 'Espoo',
    state: '',
    country: 'Finland',
    index: 49.4,
  },
  'pittsburgh-pa-united states': {
    city: 'Pittsburgh',
    state: 'PA',
    country: 'United States',
    index: 53.8,
  },
  'aarhus-denmark': {
    city: 'Aarhus',
    state: '',
    country: 'Denmark',
    index: 49.9,
  },
  'amsterdam-netherlands': {
    city: 'Amsterdam',
    state: '',
    country: 'Netherlands',
    index: 59,
  },
  'nashville-tn-united states': {
    city: 'Nashville',
    state: 'TN',
    country: 'United States',
    index: 58.3,
  },
  'minneapolis-mn-united states': {
    city: 'Minneapolis',
    state: 'MN',
    country: 'United States',
    index: 53.2,
  },
  'victoria-canada': {
    city: 'Victoria',
    state: '',
    country: 'Canada',
    index: 54.2,
  },
  'jerusalem-israel': {
    city: 'Jerusalem',
    state: '',
    country: 'Israel',
    index: 52.2,
  },
  'seoul-south korea': {
    city: 'Seoul',
    state: '',
    country: 'South Korea',
    index: 48.1,
  },
  'columbus-oh-united states': {
    city: 'Columbus',
    state: 'OH',
    country: 'United States',
    index: 53.2,
  },
  'dallas-tx-united states': {
    city: 'Dallas',
    state: 'TX',
    country: 'United States',
    index: 56.7,
  },
  'orlando-fl-united states': {
    city: 'Orlando',
    state: 'FL',
    country: 'United States',
    index: 56.5,
  },
  'munich-germany': {
    city: 'Munich',
    state: '',
    country: 'Germany',
    index: 53.1,
  },
  'baltimore-md-united states': {
    city: 'Baltimore',
    state: 'MD',
    country: 'United States',
    index: 54.7,
  },
  'haarlem-netherlands': {
    city: 'Haarlem',
    state: '',
    country: 'Netherlands',
    index: 51.3,
  },
  'salzburg-austria': {
    city: 'Salzburg',
    state: '',
    country: 'Austria',
    index: 48.7,
  },
  'luxembourg-luxembourg': {
    city: 'Luxembourg',
    state: '',
    country: 'Luxembourg',
    index: 56.2,
  },
  'dublin-ireland': {
    city: 'Dublin',
    state: '',
    country: 'Ireland',
    index: 58.5,
  },
  'edinburgh-united kingdom': {
    city: 'Edinburgh',
    state: '',
    country: 'United Kingdom',
    index: 52,
  },
  'adelaide-australia': {
    city: 'Adelaide',
    state: '',
    country: 'Australia',
    index: 49.6,
  },
  'brighton-united kingdom': {
    city: 'Brighton',
    state: '',
    country: 'United Kingdom',
    index: 54.1,
  },
  'vancouver-canada': {
    city: 'Vancouver',
    state: '',
    country: 'Canada',
    index: 56.8,
  },
  'madison-wi-united states': {
    city: 'Madison',
    state: 'WI',
    country: 'United States',
    index: 53.4,
  },
  'wellington-new zealand': {
    city: 'Wellington',
    state: '',
    country: 'New Zealand',
    index: 51.1,
  },
  'helsinki-finland': {
    city: 'Helsinki',
    state: '',
    country: 'Finland',
    index: 46.3,
  },
  'las vegas-nv-united states': {
    city: 'Las Vegas',
    state: 'NV',
    country: 'United States',
    index: 52,
  },
  'cork-ireland': {
    city: 'Cork',
    state: '',
    country: 'Ireland',
    index: 52.1,
  },
  'newcastle-australia': {
    city: 'Newcastle',
    state: '',
    country: 'Australia',
    index: 48.4,
  },
  'tucson-az-united states': {
    city: 'Tucson',
    state: 'AZ',
    country: 'United States',
    index: 49.3,
  },
  'frankfurt-germany': {
    city: 'Frankfurt',
    state: '',
    country: 'Germany',
    index: 48.8,
  },
  'perth-australia': {
    city: 'Perth',
    state: '',
    country: 'Australia',
    index: 49.6,
  },
  'hamburg-germany': {
    city: 'Hamburg',
    state: '',
    country: 'Germany',
    index: 47.1,
  },
  'darmstadt-germany': {
    city: 'Darmstadt',
    state: '',
    country: 'Germany',
    index: 47.2,
  },
  'haifa-israel': {
    city: 'Haifa',
    state: '',
    country: 'Israel',
    index: 43.7,
  },
  'melbourne-australia': {
    city: 'Melbourne',
    state: '',
    country: 'Australia',
    index: 50.3,
  },
  'phoenix-az-united states': {
    city: 'Phoenix',
    state: 'AZ',
    country: 'United States',
    index: 51.6,
  },
  'trier-germany': {
    city: 'Trier',
    state: '',
    country: 'Germany',
    index: 43.5,
  },
  'milan-italy': {
    city: 'Milan',
    state: '',
    country: 'Italy',
    index: 50.4,
  },
  'toronto-canada': {
    city: 'Toronto',
    state: '',
    country: 'Canada',
    index: 53.4,
  },
  'lyon-france': {
    city: 'Lyon',
    state: '',
    country: 'France',
    index: 44,
  },
  'kelowna-canada': {
    city: 'Kelowna',
    state: '',
    country: 'Canada',
    index: 48.8,
  },
  'heidelberg-germany': {
    city: 'Heidelberg',
    state: '',
    country: 'Germany',
    index: 47.3,
  },
  'calgary-canada': {
    city: 'Calgary',
    state: '',
    country: 'Canada',
    index: 48.7,
  },
  'hamilton-canada': {
    city: 'Hamilton',
    state: '',
    country: 'Canada',
    index: 48.1,
  },
  'austin-tx-united states': {
    city: 'Austin',
    state: 'TX',
    country: 'United States',
    index: 57.8,
  },
  'salt lake city-ut-united states': {
    city: 'Salt Lake City',
    state: 'UT',
    country: 'United States',
    index: 51.6,
  },
  'dusseldorf-germany': {
    city: 'Dusseldorf',
    state: '',
    country: 'Germany',
    index: 46.1,
  },
  'stockholm-sweden': {
    city: 'Stockholm',
    state: '',
    country: 'Sweden',
    index: 48,
  },
  'brussels-belgium': {
    city: 'Brussels',
    state: '',
    country: 'Belgium',
    index: 47,
  },
  'san antonio-tx-united states': {
    city: 'San Antonio',
    state: 'TX',
    country: 'United States',
    index: 50.2,
  },
  'manchester-united kingdom': {
    city: 'Manchester',
    state: '',
    country: 'United Kingdom',
    index: 48.6,
  },
  'auckland-new zealand': {
    city: 'Auckland',
    state: '',
    country: 'New Zealand',
    index: 48,
  },
  'vienna-austria': {
    city: 'Vienna',
    state: '',
    country: 'Austria',
    index: 45.9,
  },
  'antwerp-belgium': {
    city: 'Antwerp',
    state: '',
    country: 'Belgium',
    index: 43.5,
  },
  'maastricht-netherlands': {
    city: 'Maastricht',
    state: '',
    country: 'Netherlands',
    index: 46.2,
  },
  'rotterdam-netherlands': {
    city: 'Rotterdam',
    state: '',
    country: 'Netherlands',
    index: 49.6,
  },
  'utrecht-netherlands': {
    city: 'Utrecht',
    state: '',
    country: 'Netherlands',
    index: 49.6,
  },
  'glasgow-united kingdom': {
    city: 'Glasgow',
    state: '',
    country: 'United Kingdom',
    index: 47.1,
  },
  'ottawa-canada': {
    city: 'Ottawa',
    state: '',
    country: 'Canada',
    index: 48,
  },
  'boise-id-united states': {
    city: 'Boise',
    state: 'ID',
    country: 'United States',
    index: 49.6,
  },
  'cologne-germany': {
    city: 'Cologne',
    state: '',
    country: 'Germany',
    index: 45.4,
  },
  'brisbane-australia': {
    city: 'Brisbane',
    state: '',
    country: 'Australia',
    index: 49.1,
  },
  'freiburg im breisgau-germany': {
    city: 'Freiburg im Breisgau',
    state: '',
    country: 'Germany',
    index: 44.6,
  },
  'aberdeen-united kingdom': {
    city: 'Aberdeen',
    state: '',
    country: 'United Kingdom',
    index: 42.9,
  },
  'stuttgart-germany': {
    city: 'Stuttgart',
    state: '',
    country: 'Germany',
    index: 45.7,
  },
  'halifax-canada': {
    city: 'Halifax',
    state: '',
    country: 'Canada',
    index: 48.4,
  },
  'houston-tx-united states': {
    city: 'Houston',
    state: 'TX',
    country: 'United States',
    index: 51.1,
  },
  'essen-germany': {
    city: 'Essen',
    state: '',
    country: 'Germany',
    index: 41.1,
  },
  'gent-belgium': {
    city: 'Gent',
    state: '',
    country: 'Belgium',
    index: 42.4,
  },
  'berlin-germany': {
    city: 'Berlin',
    state: '',
    country: 'Germany',
    index: 46.9,
  },
  'graz-austria': {
    city: 'Graz',
    state: '',
    country: 'Austria',
    index: 42,
  },
  'montreal-canada': {
    city: 'Montreal',
    state: '',
    country: 'Canada',
    index: 45.7,
  },
  'jacksonville-fl-united states': {
    city: 'Jacksonville',
    state: 'FL',
    country: 'United States',
    index: 50.2,
  },
  'karlsruhe-germany': {
    city: 'Karlsruhe',
    state: '',
    country: 'Germany',
    index: 44,
  },
  'bonn-germany': {
    city: 'Bonn',
    state: '',
    country: 'Germany',
    index: 43.3,
  },
  'almere-netherlands': {
    city: 'Almere',
    state: '',
    country: 'Netherlands',
    index: 44.9,
  },
  'nuremberg-germany': {
    city: 'Nuremberg',
    state: '',
    country: 'Germany',
    index: 42.4,
  },
  'leiden-netherlands': {
    city: 'Leiden',
    state: '',
    country: 'Netherlands',
    index: 47,
  },
  'bologna-italy': {
    city: 'Bologna',
    state: '',
    country: 'Italy',
    index: 43.4,
  },
  'toulouse-france': {
    city: 'Toulouse',
    state: '',
    country: 'France',
    index: 41,
  },
  'montpellier-france': {
    city: 'Montpellier',
    state: '',
    country: 'France',
    index: 40,
  },
  'quebec city-canada': {
    city: 'Quebec City',
    state: '',
    country: 'Canada',
    index: 41.9,
  },
  'bremen-germany': {
    city: 'Bremen',
    state: '',
    country: 'Germany',
    index: 40.9,
  },
  'eindhoven-netherlands': {
    city: 'Eindhoven',
    state: '',
    country: 'Netherlands',
    index: 46.1,
  },
  'hanover-germany': {
    city: 'Hanover',
    state: '',
    country: 'Germany',
    index: 41.4,
  },
  'dortmund-germany': {
    city: 'Dortmund',
    state: '',
    country: 'Germany',
    index: 40.4,
  },
  'leeds-united kingdom': {
    city: 'Leeds',
    state: '',
    country: 'United Kingdom',
    index: 45,
  },
  'liverpool-united kingdom': {
    city: 'Liverpool',
    state: '',
    country: 'United Kingdom',
    index: 43.2,
  },
  'tampere-finland': {
    city: 'Tampere',
    state: '',
    country: 'Finland',
    index: 40.8,
  },
  'delft-netherlands': {
    city: 'Delft',
    state: '',
    country: 'Netherlands',
    index: 46.6,
  },
  'mississauga-canada': {
    city: 'Mississauga',
    state: '',
    country: 'Canada',
    index: 49.9,
  },
  'the hague (den haag)-netherlands': {
    city: 'The Hague (Den Haag)',
    state: '',
    country: 'Netherlands',
    index: 47.8,
  },
  'dubai-united arab emirates': {
    city: 'Dubai',
    state: '',
    country: 'United Arab Emirates',
    index: 55,
  },
  'mannheim-germany': {
    city: 'Mannheim',
    state: '',
    country: 'Germany',
    index: 40.9,
  },
  'edmonton-canada': {
    city: 'Edmonton',
    state: '',
    country: 'Canada',
    index: 43.4,
  },
  'christchurch-new zealand': {
    city: 'Christchurch',
    state: '',
    country: 'New Zealand',
    index: 44.3,
  },
  'erlangen-germany': {
    city: 'Erlangen',
    state: '',
    country: 'Germany',
    index: 41.2,
  },
  'newcastle upon tyne-united kingdom': {
    city: 'Newcastle upon Tyne',
    state: '',
    country: 'United Kingdom',
    index: 41.6,
  },
  'birmingham-united kingdom': {
    city: 'Birmingham',
    state: '',
    country: 'United Kingdom',
    index: 44.5,
  },
  'leipzig-germany': {
    city: 'Leipzig',
    state: '',
    country: 'Germany',
    index: 39.2,
  },
  'aachen-germany': {
    city: 'Aachen',
    state: '',
    country: 'Germany',
    index: 39.3,
  },
  'regina-canada': {
    city: 'Regina',
    state: '',
    country: 'Canada',
    index: 40.5,
  },
  'macao-macao (china)': {
    city: 'Macao',
    state: '',
    country: 'Macao (China)',
    index: 42.9,
  },
  'winnipeg-canada': {
    city: 'Winnipeg',
    state: '',
    country: 'Canada',
    index: 41.1,
  },
  'dresden-germany': {
    city: 'Dresden',
    state: '',
    country: 'Germany',
    index: 38.9,
  },
  'malmo-sweden': {
    city: 'Malmo',
    state: '',
    country: 'Sweden',
    index: 39.7,
  },
  'gothenburg-sweden': {
    city: 'Gothenburg',
    state: '',
    country: 'Sweden',
    index: 40,
  },
  'belfast-united kingdom': {
    city: 'Belfast',
    state: '',
    country: 'United Kingdom',
    index: 41.5,
  },
  'sliema-malta': {
    city: 'Sliema',
    state: '',
    country: 'Malta',
    index: 43.6,
  },
  'london-canada': {
    city: 'London',
    state: '',
    country: 'Canada',
    index: 44.9,
  },
  'cincinnati-oh-united states': {
    city: 'Cincinnati',
    state: 'OH',
    country: 'United States',
    index: 45.6,
  },
  'kingston-jamaica': {
    city: 'Kingston',
    state: '',
    country: 'Jamaica',
    index: 40.5,
  },
  'limassol-cyprus': {
    city: 'Limassol',
    state: '',
    country: 'Cyprus',
    index: 45.3,
  },
  'groningen-netherlands': {
    city: 'Groningen',
    state: '',
    country: 'Netherlands',
    index: 39.5,
  },
  'leuven-belgium': {
    city: 'Leuven',
    state: '',
    country: 'Belgium',
    index: 40.1,
  },
  'tokyo-japan': {
    city: 'Tokyo',
    state: '',
    country: 'Japan',
    index: 41.8,
  },
  'padova-italy': {
    city: 'Padova',
    state: '',
    country: 'Italy',
    index: 39.2,
  },
  'port of spain-trinidad and tobago': {
    city: 'Port of Spain',
    state: '',
    country: 'Trinidad And Tobago',
    index: 37.1,
  },
  'verona-italy': {
    city: 'Verona',
    state: '',
    country: 'Italy',
    index: 38.3,
  },
  'tallinn-estonia': {
    city: 'Tallinn',
    state: '',
    country: 'Estonia',
    index: 36.5,
  },
  'abu dhabi-united arab emirates': {
    city: 'Abu Dhabi',
    state: '',
    country: 'United Arab Emirates',
    index: 44.7,
  },
  'turin-italy': {
    city: 'Turin',
    state: '',
    country: 'Italy',
    index: 36,
  },
  'barcelona-spain': {
    city: 'Barcelona',
    state: '',
    country: 'Spain',
    index: 41.6,
  },
  'rome-italy': {
    city: 'Rome',
    state: '',
    country: 'Italy',
    index: 40.2,
  },
  'san jose-costa rica': {
    city: 'San Jose',
    state: '',
    country: 'Costa Rica',
    index: 36.4,
  },
  'naples-italy': {
    city: 'Naples',
    state: '',
    country: 'Italy',
    index: 37.1,
  },
  'madrid-spain': {
    city: 'Madrid',
    state: '',
    country: 'Spain',
    index: 41.3,
  },
  'ljubljana-slovenia': {
    city: 'Ljubljana',
    state: '',
    country: 'Slovenia',
    index: 36.9,
  },
  'athens-greece': {
    city: 'Athens',
    state: '',
    country: 'Greece',
    index: 33.8,
  },
  'nicosia-cyprus': {
    city: 'Nicosia',
    state: '',
    country: 'Cyprus',
    index: 34.2,
  },
  'larnaca-cyprus': {
    city: 'Larnaca',
    state: '',
    country: 'Cyprus',
    index: 35.7,
  },
  'montevideo-uruguay': {
    city: 'Montevideo',
    state: '',
    country: 'Uruguay',
    index: 32.1,
  },
  'kampala-uganda': {
    city: 'Kampala',
    state: '',
    country: 'Uganda',
    index: 31.2,
  },
  'bari-italy': {
    city: 'Bari',
    state: '',
    country: 'Italy',
    index: 33.6,
  },
  'taipei-taiwan': {
    city: 'Taipei',
    state: '',
    country: 'Taiwan',
    index: 34.4,
  },
  'thessaloniki-greece': {
    city: 'Thessaloniki',
    state: '',
    country: 'Greece',
    index: 31.5,
  },
  'doha-qatar': {
    city: 'Doha',
    state: '',
    country: 'Qatar',
    index: 41.3,
  },
  'sharjah-united arab emirates': {
    city: 'Sharjah',
    state: '',
    country: 'United Arab Emirates',
    index: 35.5,
  },
  'split-croatia': {
    city: 'Split',
    state: '',
    country: 'Croatia',
    index: 34.2,
  },
  'prague-czech republic': {
    city: 'Prague',
    state: '',
    country: 'Czech Republic',
    index: 37,
  },
  'manama-bahrain': {
    city: 'Manama',
    state: '',
    country: 'Bahrain',
    index: 34.5,
  },
  'riyadh-saudi arabia': {
    city: 'Riyadh',
    state: '',
    country: 'Saudi Arabia',
    index: 36.2,
  },
  'tartu-estonia': {
    city: 'Tartu',
    state: '',
    country: 'Estonia',
    index: 31.3,
  },
  'bratislava-slovakia': {
    city: 'Bratislava',
    state: '',
    country: 'Slovakia',
    index: 33.2,
  },
  'lisbon-portugal': {
    city: 'Lisbon',
    state: '',
    country: 'Portugal',
    index: 40.3,
  },
  'al khobar-saudi arabia': {
    city: 'Al Khobar',
    state: '',
    country: 'Saudi Arabia',
    index: 30.7,
  },
  'riga-latvia': {
    city: 'Riga',
    state: '',
    country: 'Latvia',
    index: 30.3,
  },
  'vilnius-lithuania': {
    city: 'Vilnius',
    state: '',
    country: 'Lithuania',
    index: 32.7,
  },
  'panama city-panama': {
    city: 'Panama City',
    state: '',
    country: 'Panama',
    index: 36.6,
  },
  'vigo-spain': {
    city: 'Vigo',
    state: '',
    country: 'Spain',
    index: 31,
  },
  'addis ababa-ethiopia': {
    city: 'Addis Ababa',
    state: '',
    country: 'Ethiopia',
    index: 31.3,
  },
  'zagreb-croatia': {
    city: 'Zagreb',
    state: '',
    country: 'Croatia',
    index: 31.4,
  },
  'kosice-slovakia': {
    city: 'Kosice',
    state: '',
    country: 'Slovakia',
    index: 30.6,
  },
  'warsaw-poland': {
    city: 'Warsaw',
    state: '',
    country: 'Poland',
    index: 34.8,
  },
  'malaga-spain': {
    city: 'Malaga',
    state: '',
    country: 'Spain',
    index: 34.6,
  },
  'seville (sevilla)-spain': {
    city: 'Seville (Sevilla)',
    state: '',
    country: 'Spain',
    index: 32.1,
  },
  'valencia-spain': {
    city: 'Valencia',
    state: '',
    country: 'Spain',
    index: 34.2,
  },
  'kaunas-lithuania': {
    city: 'Kaunas',
    state: '',
    country: 'Lithuania',
    index: 29.3,
  },
  'porto-portugal': {
    city: 'Porto',
    state: '',
    country: 'Portugal',
    index: 34.9,
  },
  'tirana-albania': {
    city: 'Tirana',
    state: '',
    country: 'Albania',
    index: 29.5,
  },
  'brno-czech republic': {
    city: 'Brno',
    state: '',
    country: 'Czech Republic',
    index: 31.1,
  },
  'jeddah (jiddah)-saudi arabia': {
    city: 'Jeddah (Jiddah)',
    state: '',
    country: 'Saudi Arabia',
    index: 28.6,
  },
  'caracas-venezuela': {
    city: 'Caracas',
    state: '',
    country: 'Venezuela',
    index: 28.2,
  },
  'kuwait city-kuwait': {
    city: 'Kuwait City',
    state: '',
    country: 'Kuwait',
    index: 33,
  },
  'beirut-lebanon': {
    city: 'Beirut',
    state: '',
    country: 'Lebanon',
    index: 31.1,
  },
  'yerevan-armenia': {
    city: 'Yerevan',
    state: '',
    country: 'Armenia',
    index: 31.4,
  },
  'plzen-czech republic': {
    city: 'Plzen',
    state: '',
    country: 'Czech Republic',
    index: 28.3,
  },
  'krakow (cracow)-poland': {
    city: 'Krakow (Cracow)',
    state: '',
    country: 'Poland',
    index: 31.6,
  },
  'monterrey-mexico': {
    city: 'Monterrey',
    state: '',
    country: 'Mexico',
    index: 31.8,
  },
  'budva-montenegro': {
    city: 'Budva',
    state: '',
    country: 'Montenegro',
    index: 32.2,
  },
  'gaborone-botswana': {
    city: 'Gaborone',
    state: '',
    country: 'Botswana',
    index: 25.6,
  },
  'santo domingo-dominican republic': {
    city: 'Santo Domingo',
    state: '',
    country: 'Dominican Republic',
    index: 30.3,
  },
  'ad dammam-saudi arabia': {
    city: 'Ad Dammam',
    state: '',
    country: 'Saudi Arabia',
    index: 26.8,
  },
  'ostrava-czech republic': {
    city: 'Ostrava',
    state: '',
    country: 'Czech Republic',
    index: 28.1,
  },
  'wroclaw-poland': {
    city: 'Wroclaw',
    state: '',
    country: 'Poland',
    index: 30.4,
  },
  'muscat-oman': {
    city: 'Muscat',
    state: '',
    country: 'Oman',
    index: 28.7,
  },
  'gdansk-poland': {
    city: 'Gdansk',
    state: '',
    country: 'Poland',
    index: 29.8,
  },
  'belgrade-serbia': {
    city: 'Belgrade',
    state: '',
    country: 'Serbia',
    index: 29.6,
  },
  'suzhou-china': {
    city: 'Suzhou',
    state: '',
    country: 'China',
    index: 26.7,
  },
  'guatemala city-guatemala': {
    city: 'Guatemala City',
    state: '',
    country: 'Guatemala',
    index: 28.3,
  },
  'istanbul-turkey': {
    city: 'Istanbul',
    state: '',
    country: 'Turkey',
    index: 30.6,
  },
  'sofia-bulgaria': {
    city: 'Sofia',
    state: '',
    country: 'Bulgaria',
    index: 27.9,
  },
  'shanghai-china': {
    city: 'Shanghai',
    state: '',
    country: 'China',
    index: 33.1,
  },
  'braga-portugal': {
    city: 'Braga',
    state: '',
    country: 'Portugal',
    index: 29.6,
  },
  'amman-jordan': {
    city: 'Amman',
    state: '',
    country: 'Jordan',
    index: 26,
  },
  'san salvador-el salvador': {
    city: 'San Salvador',
    state: '',
    country: 'El Salvador',
    index: 29.9,
  },
  'katowice-poland': {
    city: 'Katowice',
    state: '',
    country: 'Poland',
    index: 27.3,
  },
  'santiago-chile': {
    city: 'Santiago',
    state: '',
    country: 'Chile',
    index: 27.2,
  },
  'bucharest-romania': {
    city: 'Bucharest',
    state: '',
    country: 'Romania',
    index: 27.2,
  },
  'poznan-poland': {
    city: 'Poznan',
    state: '',
    country: 'Poland',
    index: 28.3,
  },
  'phuket-thailand': {
    city: 'Phuket',
    state: '',
    country: 'Thailand',
    index: 29.9,
  },
  'budapest-hungary': {
    city: 'Budapest',
    state: '',
    country: 'Hungary',
    index: 27.6,
  },
  'osijek-croatia': {
    city: 'Osijek',
    state: '',
    country: 'Croatia',
    index: 26,
  },
  'mexico city-mexico': {
    city: 'Mexico City',
    state: '',
    country: 'Mexico',
    index: 30.8,
  },
  'buenos aires-argentina': {
    city: 'Buenos Aires',
    state: '',
    country: 'Argentina',
    index: 26.7,
  },
  'lodz-poland': {
    city: 'Lodz',
    state: '',
    country: 'Poland',
    index: 26.6,
  },
  'constanta-romania': {
    city: 'Constanta',
    state: '',
    country: 'Romania',
    index: 26.2,
  },
  'novi sad-serbia': {
    city: 'Novi Sad',
    state: '',
    country: 'Serbia',
    index: 26.3,
  },
  'cluj-napoca-romania': {
    city: 'Cluj-Napoca',
    state: '',
    country: 'Romania',
    index: 26.6,
  },
  'bangkok-thailand': {
    city: 'Bangkok',
    state: '',
    country: 'Thailand',
    index: 27.8,
  },
  'phnom penh-cambodia': {
    city: 'Phnom Penh',
    state: '',
    country: 'Cambodia',
    index: 25.5,
  },
  'harare-zimbabwe': {
    city: 'Harare',
    state: '',
    country: 'Zimbabwe',
    index: 25.1,
  },
  'beijing-china': {
    city: 'Beijing',
    state: '',
    country: 'China',
    index: 30.1,
  },
  'kigali-rwanda': {
    city: 'Kigali',
    state: '',
    country: 'Rwanda',
    index: 24.8,
  },
  'shenzhen-china': {
    city: 'Shenzhen',
    state: '',
    country: 'China',
    index: 28,
  },
  'varna-bulgaria': {
    city: 'Varna',
    state: '',
    country: 'Bulgaria',
    index: 24.9,
  },
  'merida-mexico': {
    city: 'Merida',
    state: '',
    country: 'Mexico',
    index: 25.8,
  },
  'podgorica-montenegro': {
    city: 'Podgorica',
    state: '',
    country: 'Montenegro',
    index: 25.8,
  },
  'szczecin-poland': {
    city: 'Szczecin',
    state: '',
    country: 'Poland',
    index: 26.3,
  },
  'brasov-romania': {
    city: 'Brasov',
    state: '',
    country: 'Romania',
    index: 24.9,
  },
  'antalya-turkey': {
    city: 'Antalya',
    state: '',
    country: 'Turkey',
    index: 25.6,
  },
  'guangzhou-china': {
    city: 'Guangzhou',
    state: '',
    country: 'China',
    index: 25.2,
  },
  'izmir-turkey': {
    city: 'Izmir',
    state: '',
    country: 'Turkey',
    index: 25,
  },
  'queretaro (santiago de querétaro)-mexico': {
    city: 'Queretaro (Santiago de Querétaro)',
    state: '',
    country: 'Mexico',
    index: 25.2,
  },
  'guayaquil-ecuador': {
    city: 'Guayaquil',
    state: '',
    country: 'Ecuador',
    index: 23,
  },
  'guadalajara-mexico': {
    city: 'Guadalajara',
    state: '',
    country: 'Mexico',
    index: 25.8,
  },
  'timisoara-romania': {
    city: 'Timisoara',
    state: '',
    country: 'Romania',
    index: 23.3,
  },
  'ankara-turkey': {
    city: 'Ankara',
    state: '',
    country: 'Turkey',
    index: 25,
  },
  'manila-philippines': {
    city: 'Manila',
    state: '',
    country: 'Philippines',
    index: 25.6,
  },
  'johannesburg-south africa': {
    city: 'Johannesburg',
    state: '',
    country: 'South Africa',
    index: 23.9,
  },
  'colombo-sri lanka': {
    city: 'Colombo',
    state: '',
    country: 'Sri Lanka',
    index: 22.9,
  },
  'oradea-romania': {
    city: 'Oradea',
    state: '',
    country: 'Romania',
    index: 22.1,
  },
  'burgas-bulgaria': {
    city: 'Burgas',
    state: '',
    country: 'Bulgaria',
    index: 23,
  },
  'iasi-romania': {
    city: 'Iasi',
    state: '',
    country: 'Romania',
    index: 22.6,
  },
  'pattaya-thailand': {
    city: 'Pattaya',
    state: '',
    country: 'Thailand',
    index: 24.2,
  },
  'banja luka-bosnia and herzegovina': {
    city: 'Banja Luka',
    state: '',
    country: 'Bosnia And Herzegovina',
    index: 21.6,
  },
  'debrecen-hungary': {
    city: 'Debrecen',
    state: '',
    country: 'Hungary',
    index: 22.7,
  },
  'plovdiv-bulgaria': {
    city: 'Plovdiv',
    state: '',
    country: 'Bulgaria',
    index: 22.3,
  },
  'kuala lumpur-malaysia': {
    city: 'Kuala Lumpur',
    state: '',
    country: 'Malaysia',
    index: 23.4,
  },
  'quito-ecuador': {
    city: 'Quito',
    state: '',
    country: 'Ecuador',
    index: 23,
  },
  'sarajevo-bosnia and herzegovina': {
    city: 'Sarajevo',
    state: '',
    country: 'Bosnia And Herzegovina',
    index: 22,
  },
  'tbilisi-georgia': {
    city: 'Tbilisi',
    state: '',
    country: 'Georgia',
    index: 25,
  },
  'hangzhou-china': {
    city: 'Hangzhou',
    state: '',
    country: 'China',
    index: 23.7,
  },
  'puebla-mexico': {
    city: 'Puebla',
    state: '',
    country: 'Mexico',
    index: 23.6,
  },
  'sibiu-romania': {
    city: 'Sibiu',
    state: '',
    country: 'Romania',
    index: 21.9,
  },
  'erbil (irbil)-iraq': {
    city: 'Erbil (Irbil)',
    state: '',
    country: 'Iraq',
    index: 22.5,
  },
  'ulaanbaatar-mongolia': {
    city: 'Ulaanbaatar',
    state: '',
    country: 'Mongolia',
    index: 24.8,
  },
  'pretoria-south africa': {
    city: 'Pretoria',
    state: '',
    country: 'South Africa',
    index: 22.5,
  },
  'cape town-south africa': {
    city: 'Cape Town',
    state: '',
    country: 'South Africa',
    index: 26,
  },
  'chisinau-moldova': {
    city: 'Chisinau',
    state: '',
    country: 'Moldova',
    index: 23.7,
  },
  'skopje-north macedonia': {
    city: 'Skopje',
    state: '',
    country: 'North Macedonia',
    index: 21.2,
  },
  'cambridge-united kingdom': {
    city: 'Cambridge',
    country: 'United Kingdom',
    index: 56.2,
  },
  'bristol-united kingdom': {
    city: 'Bristol',
    country: 'United Kingdom',
    index: 50.6,
  },
  'st-louis-usa': {
    city: 'St. Louis',
    state: 'MO',
    country: 'United States',
    index: 49.3,
  },
  'moscow-russia': {
    city: 'Moscow',
    state: '',
    country: 'Russia',
    index: 26.9,
  },
  'lima-peru': {
    city: 'Lima',
    state: '',
    country: 'Peru',
    index: 23,
  },
  'casablanca-morocco': {
    city: 'Casablanca',
    state: '',
    country: 'Morocco',
    index: 22.2,
  },
  'bursa-turkey': {
    city: 'Bursa',
    state: '',
    country: 'Turkey',
    index: 21.7,
  },
  'accra-ghana': {
    city: 'Accra',
    state: '',
    country: 'Ghana',
    index: 22.5,
  },
  'baghdad-iraq': {
    city: 'Baghdad',
    state: '',
    country: 'Iraq',
    index: 22,
  },
  'nis-serbia': {
    city: 'Nis',
    state: '',
    country: 'Serbia',
    index: 20.3,
  },
  'sao paulo-brazil': {
    city: 'Sao Paulo',
    state: '',
    country: 'Brazil',
    index: 22.8,
  },
  'baku-azerbaijan': {
    city: 'Baku',
    state: '',
    country: 'Azerbaijan',
    index: 21.6,
  },
  'windhoek-namibia': {
    city: 'Windhoek',
    state: '',
    country: 'Namibia',
    index: 23.2,
  },
  'nairobi-kenya': {
    city: 'Nairobi',
    state: '',
    country: 'Kenya',
    index: 21.6,
  },
  'lagos-nigeria': {
    city: 'Lagos',
    state: '',
    country: 'Nigeria',
    index: 27.7,
  },
  'nanjing-china': {
    city: 'Nanjing',
    state: '',
    country: 'China',
    index: 21.2,
  },
  'rabat-morocco': {
    city: 'Rabat',
    state: '',
    country: 'Morocco',
    index: 21.5,
  },
  'durban-south africa': {
    city: 'Durban',
    state: '',
    country: 'South Africa',
    index: 20.6,
  },
  'marrakech-morocco': {
    city: 'Marrakech',
    state: '',
    country: 'Morocco',
    index: 19.5,
  },
  'mersin-turkey': {
    city: 'Mersin',
    state: '',
    country: 'Turkey',
    index: 20.3,
  },
  'chiang mai-thailand': {
    city: 'Chiang Mai',
    state: '',
    country: 'Thailand',
    index: 20.1,
  },
  'jakarta-indonesia': {
    city: 'Jakarta',
    state: '',
    country: 'Indonesia',
    index: 21.7,
  },
  'cuenca-ecuador': {
    city: 'Cuenca',
    state: '',
    country: 'Ecuador',
    index: 19.9,
  },
  'wuhan-china': {
    city: 'Wuhan',
    state: '',
    country: 'China',
    index: 19.5,
  },
  'rio de janeiro-brazil': {
    city: 'Rio de Janeiro',
    state: '',
    country: 'Brazil',
    index: 20,
  },
  'batumi-ajara-georgia': {
    city: 'Batumi',
    state: 'Ajara',
    country: 'Georgia',
    index: 20.9,
  },
  'ho chi minh city-vietnam': {
    city: 'Ho Chi Minh City',
    state: '',
    country: 'Vietnam',
    index: 20.8,
  },
  'brasilia-brazil': {
    city: 'Brasilia',
    state: '',
    country: 'Brazil',
    index: 19.7,
  },
  'chengdu-china': {
    city: 'Chengdu',
    state: '',
    country: 'China',
    index: 18.4,
  },
  'hanoi-vietnam': {
    city: 'Hanoi',
    state: '',
    country: 'Vietnam',
    index: 19.7,
  },
  'kiev (kyiv)-ukraine': {
    city: 'Kiev (Kyiv)',
    state: '',
    country: 'Ukraine',
    index: 21,
  },
  'florianopolis-brazil': {
    city: 'Florianopolis',
    state: '',
    country: 'Brazil',
    index: 19.8,
  },
  'almaty-kazakhstan': {
    city: 'Almaty',
    state: '',
    country: 'Kazakhstan',
    index: 21.3,
  },
  'medellin-colombia': {
    city: 'Medellin',
    state: '',
    country: 'Colombia',
    index: 20,
  },
  'tunis-tunisia': {
    city: 'Tunis',
    state: '',
    country: 'Tunisia',
    index: 17.6,
  },
  'saint petersburg-russia': {
    city: 'Saint Petersburg',
    state: '',
    country: 'Russia',
    index: 20.6,
  },
  'campinas-brazil': {
    city: 'Campinas',
    state: '',
    country: 'Brazil',
    index: 18.9,
  },
  'dar es salaam-tanzania': {
    city: 'Dar es Salaam',
    state: '',
    country: 'Tanzania',
    index: 20.9,
  },
  'porto alegre-brazil': {
    city: 'Porto Alegre',
    state: '',
    country: 'Brazil',
    index: 18.4,
  },
  'astana (nur-sultan)-kazakhstan': {
    city: 'Astana (Nur-Sultan)',
    state: '',
    country: 'Kazakhstan',
    index: 19.2,
  },
  'fortaleza-brazil': {
    city: 'Fortaleza',
    state: '',
    country: 'Brazil',
    index: 17,
  },
  'belo horizonte-brazil': {
    city: 'Belo Horizonte',
    state: '',
    country: 'Brazil',
    index: 18.2,
  },
  'tehran-iran': {
    city: 'Tehran',
    state: '',
    country: 'Iran',
    index: 20.1,
  },
  'algiers-algeria': {
    city: 'Algiers',
    state: '',
    country: 'Algeria',
    index: 16.6,
  },
  'bishkek-kyrgyzstan': {
    city: 'Bishkek',
    state: '',
    country: 'Kyrgyzstan',
    index: 19.3,
  },
  'vladivostok-russia': {
    city: 'Vladivostok',
    state: '',
    country: 'Russia',
    index: 19,
  },
  'dnipro-ukraine': {
    city: 'Dnipro',
    state: '',
    country: 'Ukraine',
    index: 19.9,
  },
  'bogota-colombia': {
    city: 'Bogota',
    state: '',
    country: 'Colombia',
    index: 18.6,
  },
  'pristina-kosovo (disputed territory)': {
    city: 'Pristina',
    state: '',
    country: 'Kosovo (Disputed Territory)',
    index: 17.6,
  },
  'minsk-belarus': {
    city: 'Minsk',
    state: '',
    country: 'Belarus',
    index: 18.6,
  },
  'curitiba-brazil': {
    city: 'Curitiba',
    state: '',
    country: 'Brazil',
    index: 17.6,
  },
  'mumbai-india': {
    city: 'Mumbai',
    state: '',
    country: 'India',
    index: 22.3,
  },
  'cali-colombia': {
    city: 'Cali',
    state: '',
    country: 'Colombia',
    index: 16.8,
  },
  'tashkent-uzbekistan': {
    city: 'Tashkent',
    state: '',
    country: 'Uzbekistan',
    index: 20.6,
  },
  'sao jose dos campos-brazil': {
    city: 'Sao Jose dos Campos',
    state: '',
    country: 'Brazil',
    index: 17.6,
  },
  'odessa (odesa)-ukraine': {
    city: 'Odessa (Odesa)',
    state: '',
    country: 'Ukraine',
    index: 16.4,
  },
  'gurgaon-india': {
    city: 'Gurgaon',
    state: '',
    country: 'India',
    index: 17.1,
  },
  'lviv-ukraine': {
    city: 'Lviv',
    state: '',
    country: 'Ukraine',
    index: 17.9,
  },
  'kathmandu-nepal': {
    city: 'Kathmandu',
    state: '',
    country: 'Nepal',
    index: 15,
  },
  'yekaterinburg-russia': {
    city: 'Yekaterinburg',
    state: '',
    country: 'Russia',
    index: 17.3,
  },
  'recife-brazil': {
    city: 'Recife',
    state: '',
    country: 'Brazil',
    index: 16.4,
  },
  'nizhny novgorod-russia': {
    city: 'Nizhny Novgorod',
    state: '',
    country: 'Russia',
    index: 16.5,
  },
  'kharkiv-ukraine': {
    city: 'Kharkiv',
    state: '',
    country: 'Ukraine',
    index: 15.3,
  },
  'samara-russia': {
    city: 'Samara',
    state: '',
    country: 'Russia',
    index: 15.6,
  },
  'tomsk-russia': {
    city: 'Tomsk',
    state: '',
    country: 'Russia',
    index: 15.8,
  },
  'bangalore-india': {
    city: 'Bangalore',
    state: '',
    country: 'India',
    index: 16.9,
  },
  'kazan-russia': {
    city: 'Kazan',
    state: '',
    country: 'Russia',
    index: 16.6,
  },
  'krasnodar-russia': {
    city: 'Krasnodar',
    state: '',
    country: 'Russia',
    index: 16.1,
  },
  'asuncion-paraguay': {
    city: 'Asuncion',
    state: '',
    country: 'Paraguay',
    index: 17.1,
  },
  'dhaka-bangladesh': {
    city: 'Dhaka',
    state: '',
    country: 'Bangladesh',
    index: 14.1,
  },
  'novosibirsk-russia': {
    city: 'Novosibirsk',
    state: '',
    country: 'Russia',
    index: 15.9,
  },
  'ufa-russia': {
    city: 'Ufa',
    state: '',
    country: 'Russia',
    index: 15.1,
  },
  'kaliningrad-russia': {
    city: 'Kaliningrad',
    state: '',
    country: 'Russia',
    index: 15.9,
  },
  'rostov-on-don (rostov-na-donu)-russia': {
    city: 'Rostov-on-Don (Rostov-na-donu)',
    state: '',
    country: 'Russia',
    index: 15.4,
  },
  'pune-india': {
    city: 'Pune',
    state: '',
    country: 'India',
    index: 15.3,
  },
  'voronezh-russia': {
    city: 'Voronezh',
    state: '',
    country: 'Russia',
    index: 14.9,
  },
  'noida-india': {
    city: 'Noida',
    state: '',
    country: 'India',
    index: 14.6,
  },
  'delhi-india': {
    city: 'Delhi',
    state: '',
    country: 'India',
    index: 15.6,
  },
  'hyderabad-india': {
    city: 'Hyderabad',
    state: '',
    country: 'India',
    index: 14.7,
  },
  'perm-russia': {
    city: 'Perm',
    state: '',
    country: 'Russia',
    index: 14.8,
  },
  'ahmedabad-india': {
    city: 'Ahmedabad',
    state: '',
    country: 'India',
    index: 13.7,
  },
  'tripoli-libya': {
    city: 'Tripoli',
    state: '',
    country: 'Libya',
    index: 13.7,
  },
  'chennai-india': {
    city: 'Chennai',
    state: '',
    country: 'India',
    index: 13.6,
  },
  'chandigarh-india': {
    city: 'Chandigarh',
    state: '',
    country: 'India',
    index: 13.1,
  },
  'vadodara-india': {
    city: 'Vadodara',
    state: '',
    country: 'India',
    index: 12.6,
  },
  'chelyabinsk-russia': {
    city: 'Chelyabinsk',
    state: '',
    country: 'Russia',
    index: 13.7,
  },
  'islamabad-pakistan': {
    city: 'Islamabad',
    state: '',
    country: 'Pakistan',
    index: 13.3,
  },
  'cairo-egypt': {
    city: 'Cairo',
    state: '',
    country: 'Egypt',
    index: 13.1,
  },
  'kolkata-india': {
    city: 'Kolkata',
    state: '',
    country: 'India',
    index: 12.5,
  },
  'bhubaneswar-india': {
    city: 'Bhubaneswar',
    state: '',
    country: 'India',
    index: 12.5,
  },
  'jaipur-india': {
    city: 'Jaipur',
    state: '',
    country: 'India',
    index: 12.4,
  },
  'surat-india': {
    city: 'Surat',
    state: '',
    country: 'India',
    index: 15.8,
  },
  'kochi-india': {
    city: 'Kochi',
    state: '',
    country: 'India',
    index: 12.6,
  },
  'bhopal-india': {
    city: 'Bhopal',
    state: '',
    country: 'India',
    index: 11.9,
  },
  'lucknow (lakhnau)-india': {
    city: 'Lucknow (Lakhnau)',
    state: '',
    country: 'India',
    index: 12.2,
  },
  'karachi-pakistan': {
    city: 'Karachi',
    state: '',
    country: 'Pakistan',
    index: 11.6,
  },
  'indore-india': {
    city: 'Indore',
    state: '',
    country: 'India',
    index: 12.2,
  },
  'alexandria-egypt': {
    city: 'Alexandria',
    state: '',
    country: 'Egypt',
    index: 11.3,
  },
  'lahore-pakistan': {
    city: 'Lahore',
    state: '',
    country: 'Pakistan',
    index: 11.6,
  },
  'coimbatore-india': {
    city: 'Coimbatore',
    state: '',
    country: 'India',
    index: 11.4,
  },
};
